In [1]:
import numpy as np
import operator

movie_data = {"宝贝当家": [45, 2, 9, "喜剧片"],
              "美人鱼": [21, 17, 5, "喜剧片"],
              "澳门风云3": [54, 9, 11, "喜剧片"],
              "功夫熊猫3": [39, 0, 31, "喜剧片"],
              "谍影重重": [5, 2, 57, "动作片"],
              "叶问3": [3, 2, 65, "动作片"],
              "伦敦陷落": [2, 3, 55, "动作片"],
              "我的特工爷爷": [6, 4, 21, "动作片"],
              "奔爱": [7, 46, 4, "爱情片"],
              "夜孔雀": [9, 39, 8, "爱情片"],
              "代理情人": [9, 38, 2, "爱情片"],
              "新步步惊心": [8, 34, 17, "爱情片"]}

In [2]:
def createDataSet():
    '''
        准备数据集
        Return
            data ： 数据
            labels ： 标签
    '''
    data = np.zeros((len(movie_data),3))
    labels = np.zeros((len(movie_data),1), dtype = 'int64')
    i = 0
    for key, value in movie_data.items():
        data[i] = value[:-1]
        if value[-1] == '喜剧片':
            c = 1
        elif value[-1] == '动作片':
            c = 2
        else:
            c = 3
        labels[i] = c
        i = i+1
    return data, labels

data, labels = createDataSet()
data, labels

(array([[45.,  2.,  9.],
        [21., 17.,  5.],
        [54.,  9., 11.],
        [39.,  0., 31.],
        [ 5.,  2., 57.],
        [ 3.,  2., 65.],
        [ 2.,  3., 55.],
        [ 6.,  4., 21.],
        [ 7., 46.,  4.],
        [ 9., 39.,  8.],
        [ 9., 38.,  2.],
        [ 8., 34., 17.]]),
 array([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]], dtype=int64))

In [3]:
x = [23, 3, 17]
dist = np.sum((data - x) **2, axis = 1) ** 0.5  #2范数
dist

array([23.43074903, 18.54723699, 32.14031736, 21.47091055, 43.87482194,
       52.0096145 , 43.41658669, 17.49285568, 47.68647607, 39.66106403,
       40.57092555, 34.43835072])

In [4]:
k_labels = np.array([labels[index] for index in dist.argsort()[0 : 5]])  #人为设定取前5个距离最小值
k_labels

array([[2],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [8]:
k_labels = np.squeeze(k_labels, axis=1)
counter = {}
for i in k_labels:
    if counter.get(i) == None:
        counter[i] = 1
    else:
        counter[i] = counter.get(i) + 1
result = sorted(counter.items(), key=operator.itemgetter(1), reverse=True)
#key=operator.itemgetter(1)根据字典的value进行排序
#key=operator.itemgetter(0)根据字典的key进行排序
#reverse降序排序字典
result[0][0]


1

In [9]:
def knn(x, data, labels, k):
    '''
        实现knn分类算法
        Arguments
            x : 输入数据
            data : 样本数据
            labels ： 样本标签
            k : 算法中k的取值
        Return
            result : 目标的种类
    '''
    dist = np.sum((data - x) **2, axis = 1) ** 0.5
    k_labels = np.array([labels[index] for index in dist.argsort()[0:k]])
    k_labels = np.squeeze(k_labels, axis=1)
    counter = {}
    for i in k_labels:
        if counter.get(i) == None:
            counter[i] = 1
        else:
            counter[i] = counter.get(i) + 1
    result = sorted(counter.items(), key=operator.itemgetter(1), reverse=True)[0][0]
    return result


In [10]:
def print_result(result):
    if result == 1:
        print('喜剧片')
    if result == 2:
        print('动作片')
    if result == 3:
        print('爱情片')

In [15]:
if __name__ == '__main__':

    data, labels = createDataSet() #创建数据集
    x = [23, 3, 17] #测试集
    result = knn(x, data, labels, 5) #kNN分类
    print_result(result) #打印分类结果

喜剧片
